// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmQ802qZzSzFAx_HzQOwBACu1M-57Ya34',
    appId: '1:115138957843:web:1f188f178c691dcecea5e6',
    messagingSenderId: '115138957843',
    projectId: 'smart-trash-app-2af97',
    authDomain: 'smart-trash-app-2af97.firebaseapp.com',
    databaseURL: 'https://smart-trash-app-2af97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-app-2af97.firebasestorage.app',
    measurementId: 'G-TDG4VGSHGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwjAh0DdE-tpJlly_4kCREY97PGkLvdLM',
    appId: '1:115138957843:android:f6b3095bdb9c3f6acea5e6',
    messagingSenderId: '115138957843',
    projectId: 'smart-trash-app-2af97',
    databaseURL: 'https://smart-trash-app-2af97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-app-2af97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmQ802qZzSzFAx_HzQOwBACu1M-57Ya34',
    appId: '1:115138957843:web:80188ffc261720a3cea5e6',
    messagingSenderId: '115138957843',
    projectId: 'smart-trash-app-2af97',
    authDomain: 'smart-trash-app-2af97.firebaseapp.com',
    databaseURL: 'https://smart-trash-app-2af97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-trash-app-2af97.firebasestorage.app',
    measurementId: 'G-E203YMYPC1',
  );

}